---

- name: add host to play
  hosts: localhost
  gather_facts: false
  tasks:
  - name: add control host
    add_host:
      name: "{{ trainer }}"
      ansible_host: "{{ trainer }}.{{ lab_domain }}"
      ansible_user: "{{ trainer }}"
      ansible_ssh_pass: "{{ lab_password }}"

- name: setup progress report server
  hosts: all
  tasks:
  - name: install awx.awx collection
    shell: |
     ansible-galaxy collection install awx.awx:19.0.0
     ansible-galaxy collection install community.general

  - name: clone down the git repo
    git:
      repo: https://github.com/pharriso/workshop_progress_report.git
      dest: /home/{{ ansible_user }}/workshop_progress_report
      force: yes

  - name: setup cron job
    cron:
      name: "check dirs"
      minute: "*/5"
      hour: "*"
      job: "ansible-playbook /home/{{ ansible_user }}/workshop_progress_report/workshop_progress_report.yml -e @/home/{{ ansible_user }}/workshop_progress_report/extra_vars  > /dev/null"

  - name: copy over vars file
    copy:
      src: extra_vars
      dest: /home/{{ ansible_user }}/workshop_progress_report/extra_vars

  - name: run report
    shell: |
      ansible-playbook /home/{{ ansible_user }}/workshop_progress_report/workshop_progress_report.yml -e @/home/{{ ansible_user }}/workshop_progress_report/extra_vars
    ignore_errors: true


  - name: print report url
    debug:
      msg: http://{{ trainer}}.{{ lab_domain}}/workshop_progress_report.html
    run_once: true
    delegate_to: localhost
